{% set version="1.0.4" %}
package:
  name: bioconductor-chimeraviz
  version: {{ version }}
source:
  fn: release-3.5.zip
  url: https://github.com/Bioconductor-mirror/chimeraviz/archive/release-3.5.zip
  md5: 129446e46040fa2cdb34854bbf837fd1

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - bioconductor-biobase
    - bioconductor-biostrings
    - 'bioconductor-biocgenerics >=0.7.5'
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-gviz
    - 'bioconductor-s4vectors >=0.9.25'
    - bioconductor-ensembldb
    - bioconductor-annotationfilter
    - r-readr
    - r-gridbase
    - r-gridextra
    - bioconductor-rsamtools
    - bioconductor-genomeinfodb
    - bioconductor-genomeinfodbdata
    - bioconductor-genomicalignments
    - r-rcolorbrewer
    - bioconductor-annotationdbi
    - r-rcircos
    - bioconductor-org.hs.eg.db
    - r-rmarkdown
    - bioconductor-graph
    - bioconductor-rgraphviz
    - r-dt
    - r-plyr
    - bioconductor-biocstyle
    - pandoc
    - r-argumentcheck
    - r-base >=3.4
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - bioconductor-biobase
    - bioconductor-biostrings
    - 'bioconductor-biocgenerics >=0.7.5'
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-gviz
    - 'bioconductor-s4vectors >=0.9.25'
    - bioconductor-ensembldb
    - bioconductor-annotationfilter
    - r-readr
    - r-gridbase
    - r-gridextra
    - bioconductor-rsamtools
    - bioconductor-genomeinfodb
    - bioconductor-genomeinfodbdata
    - bioconductor-genomicalignments
    - r-rcolorbrewer
    - bioconductor-annotationdbi
    - r-rcircos
    - bioconductor-org.hs.eg.db
    - r-rmarkdown
    - bioconductor-graph
    - bioconductor-rgraphviz
    - r-dt
    - r-plyr
    - bioconductor-biocstyle
    - pandoc
    - r-argumentcheck
    - r-base >=3.4
    - gcc  # [linux]
    - llvm  # [osx]

test:
  commands:
    - '$R -e "library(''chimeraviz'')"'
about:
  home: https://bioconductor.org/packages/release/bioc/html/chimeraviz.html
  license: 'Artistic-2.0'
  summary: 'chimeraviz manages data from fusion gene finders and provides useful visualization tools.'
